app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    Route::get('/',['as'=>'root','uses'=>'PagesController@welcome']);
    Route::get('/login',['middleware'=>'guest','as'=>'login','uses'=>'AuthController@login']);
    Route::post('/handlelogin',['as'=>'handlelogin','uses'=>'AuthController@handle_login']);
    Route::get('/home',['middleware'=>'auth','as' => 'home','uses' => 'UsersController@home']);
    Route::get('/logout',['middleware'=>'auth','as'=>'logout','uses'=>'AuthController@logout']);

    Route::get('/like/{id}',['middleware'=>'auth','as'=>'like','uses'=>'PostsController@like']);
    Route::get('/unlike/{id}',['middleware'=>'auth','as'=>'unlike','uses'=>'PostsController@unlike']);

    Route::resource('users','UsersController',['only'=>['create','store']]);
    Route::resource('posts','PostsController');
    Route::get('/{username}',['as'=>'UserPosts','uses'=>'UsersController@listPosts']);
});

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>InnFact | Blogging begins here</title>
	<link rel="stylesheet" href="{{ URL::asset('css/app.css') }}">
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			{{ link_to_route('root','InnFact',null,array('class' => 'navbar-brand')) }}
		</div>
		<ul class="navbar-nav nav navbar-right">
			@if(\Auth::check())
				<li>{{ link_to_route('posts.create', 'Compose Post') }}</li>
				<li><a href="#">Logged in as {{ \Auth::user()->name }}</a></li>
				<li>{{ link_to_route('logout', 'Log Out') }}</li>
			@else
				<li>{{ link_to_route('users.create','Sign Up')}}</li>
				<li>{{ link_to_route('login','Sign In')}}</li>
			@endif
		</ul>
	</div>
</nav>
<div class="container">
	@yield('content')
</div>
</body>
</html>